insert into movies (    id,                                              name,               year, imdb_score,                                imdb_url)
            values (uuid(),                           'Um Sonho de Liberdade',               1994,        9.2, 'https://www.imdb.com/title/tt0111161/'),
                   (uuid(),                          'O Cavaleiro das Trevas',               2008,        9.0, 'https://www.imdb.com/title/tt0468569/'),
                   (uuid(),                            'A Lista de Schindler',               1993,        8.9, 'https://www.imdb.com/title/tt0108052/'),
                   (uuid(),          'O Senhor do Anéis: A Sociedade do Anel',               2001,        8.8, 'https://www.imdb.com/title/tt0120737/'),
                   (uuid(),              'O Senhor dos Anéis: As Duas Torres',               2020,        8.7, 'https://www.imdb.com/title/tt0167261/'),
                   (uuid(),            'O Senhor dos Anéis: O Retorno do Rei',               2003,        8.9, 'https://www.imdb.com/title/tt0167260/'),
                   (uuid(),                                    'Pulp Fiction',               1994,        8.8, 'https://www.imdb.com/title/tt0110912/'),
                   (uuid(),                                   'Clube da Luta',               1999,        8.8, 'https://www.imdb.com/title/tt0137523/'),
                   (uuid(),           'Forrest Gump: O Contador de Histórias',               1999,        8.8, 'https://www.imdb.com/title/tt0109830/'),
                   (uuid(),                                        'A Origem',               2010,        8.7, 'https://www.imdb.com/title/tt1375666/'),
                   (uuid(),     'Star Wars: Episódio IV - Uma Nova Esperança',               1977,        8.6, 'https://www.imdb.com/title/tt0076759/'),
                   (uuid(),  'Star Wars: Episódio V - O Império Contra Ataca',               1980,        8.7, 'https://www.imdb.com/title/tt0080684/'),
                   (uuid(),      'Star Wars: Episódio VI - O Retorno de Jedi',               1983,        8.3, 'https://www.imdb.com/title/tt0086190/'),
                   (uuid(),                                          'Matrix',               1999,        8.6, 'https://www.imdb.com/title/tt0133093/'),
                   (uuid(),                                   'A Vida é Bela',               1997,        8.6, 'https://www.imdb.com/title/tt0118799/'),
                   (uuid(),                       'O Resgate do Soldado Rian',               1998,        8.6, 'https://www.imdb.com/title/tt0120815/'),
                   (uuid(),                                    'Interstellar',               2014,        8.5, 'https://www.imdb.com/title/tt0816692/'),
                   (uuid(),                                        'Parasita',               2019,        8.5, 'https://www.imdb.com/title/tt6751668/'),
                   (uuid(),                                         'Bacurau',               2019,        8.5, 'https://www.imdb.com/title/tt2762506/'),
                   (uuid(),                                  'Cidade de Deus',               2002,        8.6, 'https://www.imdb.com/title/tt0317248/'),
                   (uuid(),                                       'Carandiru',               2019,        7.6, 'https://www.imdb.com/title/tt0293007/'),
                   (uuid(),                               'Central do Brasil',               1998,        8.0, 'https://www.imdb.com/title/tt0140888/'),
                   (uuid(),                             'Que Horas Ela Volta',               2015,        7.8, 'https://www.imdb.com/title/tt3742378/'),
                   (uuid(),                           'O Auto da Compadecida',               2000,        8.7, 'https://www.imdb.com/title/tt0271383/');
